PREFIX humans: <http://www.inria.fr/2007/09/11/humans.rdfs#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?husband ?wife
WHERE
{
 ?husband humans:hasSpouse ?wife .
 ?husband rdf:type humans:Man
}
