PREFIX humans: <http://www.inria.fr/2007/09/11/humans.rdfs#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mark: <http://www.inria.fr/2007/09/11/humans.rdfs-instances#Mark>

ASK
WHERE
{ 
	?mark humans:age ?age
	FILTER ( xsd:integer(?age) >= 14 )
}


